apiVersion: 1

datasources:
  - name: Thanos
    uid: thanos
    type: prometheus
    access: proxy
    url: http://thanos-query:9090
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Prometheus-use1-1
    type: prometheus
    access: proxy
    url: http://prometheus-use1-1:9090
    jsonData:
      timeInterval: 15s

  - name: Prometheus-use1-2
    type: prometheus
    access: proxy
    url: http://prometheus-use1-2:9090
    jsonData:
      timeInterval: 15s

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    jsonData:
      implementation: prometheus

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "(?:traceID|trace_id)=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
        tags:
          - key: service.name
            value: container
      tracesToMetrics:
        datasourceUid: thanos
        tags:
          - key: service.name
            value: job
        queries:
          - name: Request rate
            query: "rate(http_server_requests_seconds_count{$$__tags}[5m])"
          - name: Error rate
            query: "rate(http_server_requests_seconds_count{$$__tags,status=~\"5..\"}[5m])"
      serviceMap:
        datasourceUid: thanos
      nodeGraph:
        enabled: true
